apiVersion: v1
clusters:
- cluster:
    server: ""
  name: tellu_monitoring
contexts:
- context:
    cluster: ""
    user: ""
  name: tellu_monitoring
current-context: ""
kind: Config
preferences: {}
users: null
