filepath: ''
environments:
 prod:
   values:
    - ../../env/prod.yaml
 default:
   values:
    - ../../env/stage.yaml


namespace: sysdig-agent
repositories:
  - name: sysdig
    url: https://charts.sysdig.com
releases:
  - chart: sysdig/agent
    version: 1.5.21
    name: agent
    values:
      - values.yaml.gotmpl
templates: {}
renderedvalues: {}
