filepath: ''
namespace: sysdig-agent
repositories:
  - name: sysdig
    url: https://charts.sysdig.com
releases:
  - chart: charts/agent
    version: v1.5.21
    name: agent
    values:
      - values.yaml
templates: {}
renderedvalues: {}
