enabled: true
global:
  clusterConfig:
    name: audit-log-test
  sysdig:
    accessKey: ''
agent:
  sysdig:
    settings:
      collector: ingest-eu1.app.sysdig.com
      collector_port: 6443
nodeAnalyser:
  nodeAnalyser:
    apiEndpoint: eu1.app.sysdig.com
    secure:
      vulnerabilityManagement:
        newEngineOnly: true
